---
layout: home
title: "Meileen Manzanilla - GIS Portfolio"
author_profile: true
---
## Welcome to My GIS Portfolio 🌍  

I am a **Geodetic Engineer** specializing in **GIS, Remote Sensing, and Spatial Analysis**.  
This portfolio showcases my work in geospatial data science, cartography, and mapping projects.  

### 🔥 Featured Project  
- **[Area Impacted by Wildfire in California (2012-2022)](/projects/wildfire-impact/)**  

Explore more in the **Projects** section. 🚀  
